-- ===================================================================
-- SCRIPT DE BANCO DE DADOS: script_bd.sql
-- Disciplina: DevOps Tools & Cloud Computing - 3ª Sprint (FIAP)
-- Projeto: Clyvo Vet - Plataforma Preditiva de Longevidade Pet
-- ===================================================================
-- Tabelas CORE da Solução: T_TUTOR e T_PET (Relacionamento 1:N)
-- Este arquivo atende aos itens 3.3 e 3.4 do edital de entrega.
-- ===================================================================

-- 1. TABELA DE RAÇAS (Suporte a predisposição genética da espécie)
CREATE TABLE T_RACA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    propensao_doenca VARCHAR2(255),
    expectativa_vida NUMBER,
    cuidados_especiais VARCHAR2(500)
);

COMMENT ON TABLE T_RACA IS 'Catálogo de raças de cães e gatos com expectativas de vida e predisposições genéticas de saúde.';
COMMENT ON COLUMN T_RACA.id IS 'Identificador numérico único sequencial da raça (Chave Primária).';
COMMENT ON COLUMN T_RACA.nome IS 'Nome da raça (ex: Golden Retriever, Buldogue Francês).';
COMMENT ON COLUMN T_RACA.propensao_doenca IS 'Condições e doenças genéticas associadas à raça.';
COMMENT ON COLUMN T_RACA.expectativa_vida IS 'Expectativa média de vida em anos da raça.';
COMMENT ON COLUMN T_RACA.cuidados_especiais IS 'Diretrizes clínicas e preventivas para a longevidade do animal.';

-- 2. TABELA CORE 1: TUTORES (Responsáveis pelos animais)
CREATE TABLE T_TUTOR (
    cpf VARCHAR2(14) PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(20),
    email VARCHAR2(100),
    qtd_pets NUMBER DEFAULT 0
);

COMMENT ON TABLE T_TUTOR IS 'Tabela CORE representando os tutores de animais cadastrados na plataforma Clyvo Vet.';
COMMENT ON COLUMN T_TUTOR.cpf IS 'Número de CPF do tutor no formato XXX.XXX.XXX-XX ou somente dígitos (Chave Primária).';
COMMENT ON COLUMN T_TUTOR.nome IS 'Nome completo do tutor.';
COMMENT ON COLUMN T_TUTOR.telefone IS 'Telefone de contato do tutor.';
COMMENT ON COLUMN T_TUTOR.email IS 'Endereço de e-mail do tutor.';
COMMENT ON COLUMN T_TUTOR.qtd_pets IS 'Contador consolidado de animais vinculados a este tutor.';

-- 3. TABELA CORE 2: PETS (Pacientes monitorados para longevidade)
CREATE TABLE T_PET (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    peso NUMBER(5,2),
    status_longevidade VARCHAR2(500),
    raca_id NUMBER,
    tutor_cpf VARCHAR2(14) NOT NULL,
    CONSTRAINT fk_pet_raca FOREIGN KEY (raca_id) REFERENCES T_RACA(id),
    CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_cpf) REFERENCES T_TUTOR(cpf) ON DELETE CASCADE
);

COMMENT ON TABLE T_PET IS 'Tabela CORE representando os pets pacientes sob monitoramento e cuidados preventivos contínuos.';
COMMENT ON COLUMN T_PET.id IS 'Identificador numérico único sequencial do pet (Chave Primária).';
COMMENT ON COLUMN T_PET.nome IS 'Nome de identificação do pet.';
COMMENT ON COLUMN T_PET.data_nascimento IS 'Data de nascimento para cálculo da idade cronológica e biológica.';
COMMENT ON COLUMN T_PET.peso IS 'Peso corporal aferido em quilogramas (ex: 28.50).';
COMMENT ON COLUMN T_PET.status_longevidade IS 'Parecer e classificação preditiva gerada pelo motor de IA preventiva.';
COMMENT ON COLUMN T_PET.raca_id IS 'Chave estrangeira referenciando a raça cadastrada na tabela T_RACA.';
COMMENT ON COLUMN T_PET.tutor_cpf IS 'Chave estrangeira referenciando o tutor responsável na tabela T_TUTOR (Chave Estrangeira 1:N).';

-- ===================================================================
-- FIM DO SCRIPT DDL
-- ===================================================================
