spring.application.name=clyvo-api

# Configuração do Banco Oracle (Suporte para Docker / Variáveis de Ambiente)
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521:XE}
spring.datasource.username=${DB_USER:RM562795}
spring.datasource.password=${DB_PASSWORD:060205}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Documentação Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Cache
spring.cache.type=concurrent
